# Generated by Django 4.2.3 on 2023-09-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2002-11-14'),
            preserve_default=False,
        ),
    ]
